dashboard alert
YasiTL/backpat pull request #13
Opened 2021-01-09 08:15 UTC by jhayes99823

- Reusable dashboard alert component

<img width="1440" alt="Screen Shot 2021-01-09 at 3 13 03 AM" src="https://user-images.githubusercontent.com/28914562/104086780-c3ad0e00-5228-11eb-8c02-5bb4f3e0bcc9.png">

2021-01-09 23:29 UTC, YasiTL requested changes
Awesome start. Just a few things to change/look over before completing. Message me on slack if you have any questions!

2021-01-09 23:29 UTC, YasiTL commented on src/components/Alert/DashboardAlert.jsx
> +  // <DashboardAlert alertOpen={alertOpen} toggleAlert={toggleAlert} type="warning" title="To complete your account and begin tutoring, please finish the following:" descriptionItems={["Send us your
I really appreciate this commenting! Nice job!

2021-01-09 23:29 UTC, YasiTL commented on src/components/Alert/DashboardAlert.jsx
> +        <Snackbar anchorOrigin={{ vertical, horizontal }} open={alertOpen} onClose={toggleAlert}>
The alert should be permanent on the page, rather than a dialog that can be dismissed. These images may help that become more clear.
![image](https://user-images.githubusercontent.com/14118065/104110693-c9920600-529f-11eb-8a5c-ff018e5e08a9.png)

2021-01-09 23:29 UTC, YasiTL commented on src/components/Home.js
> +import DashboardAlert from './Alert/DashboardAlert';
Remove unused imports to avoid build warnings on pull requests.

2021-01-14 04:12 UTC, jhayes99823 commented on src/components/Home.js
> +import DashboardAlert from './Alert/DashboardAlert';
Should be fixed

2021-01-14 04:12 UTC, jhayes99823 commented on src/components/Alert/DashboardAlert.jsx
> +        <Snackbar anchorOrigin={{ vertical, horizontal }} open={alertOpen} onClose={toggleAlert}>
![image](https://user-images.githubusercontent.com/28914562/104544033-dd699f00-55f4-11eb-9e6b-569e929d344e.png)

2021-01-14 16:01 UTC, YasiTL approved these changes
Beautiful! Nice job.

2021-01-14 16:01 UTC, merged