Add files via upload
YasiTL/backpat pull request #4
Opened 2020-08-31 17:22 UTC by AlirpJ

attempting to create tutor login page and understand how to navigate to that page

this pull request actually works unlike the last one. I don't understand how router or link work (those are new things, I think for accessing other web pages?)

changes:

tutorLogin.js file. Has a way for users to enter an email and password(?)
App.js comment and imports tutorLogin
index.js imports from react-router-dom

2020-09-01 23:53 UTC, YasiTL requested changes
Great work on the tutorLogin.js component, and nice job using form groups and state. We might have to talk about that component, but for now, it works.

- [ ]  pull master to get routes, and to see the ParentSignUp component example with `git pull origin master`
- [ ] Make a TutorSignUp.js component
- [ ] implement your login component in TutorSignUp.js Component (optional for now, but reccomended)

obviously, if this doesnt make sense or you have any questions, reply to this thread or message me on slack!

2020-09-01 23:53 UTC, YasiTL commented on index.js
> +import React from 'react';
This file is unneeded, index.js in src is sufficient.

2020-09-01 23:53 UTC, YasiTL commented on App.js
> +import React from 'react';
This file is unneeded, App.js in src is sufficient.

2020-09-01 23:53 UTC, YasiTL commented on tutorLogin.js
> +import React, { useState } from "react";
ensure this file ends up in the component folder

2020-09-03 04:27 UTC, AlirpJ commented on App.js
> +import React from 'react';
Would this file not just overwrite the current App.js?

2020-09-03 04:28 UTC, AlirpJ commented on index.js
> +import React from 'react';
See other comment, I'm looking to overwrite

2020-09-03 04:28 UTC, AlirpJ commented
@YasiTL I'm not sure how to edit a pull request (if it wasn't noticed, this is the second I submitted. Changes made from the first)

2020-09-03 04:29 UTC, AlirpJ commented on tutorLogin.js
> +import React, { useState } from "react";
Maybe I'll just cancel this pull request and make a new one lol

2020-09-03 04:34 UTC, AlirpJ commented
**pull master to get routes, and to see the ParentSignUp component example with git pull origin master**

I'm not sure what this means

 **Make a TutorSignUp.js component**

This is for allowing tutors to create new accounts?

 **implement your login component in TutorSignUp.js Component (optional for now, but reccomended)**

Noted

2020-09-06 15:41 UTC, closed without merging